# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="jj"

export HOMEBREW_NO_ANALYTICS=1
eval $(/opt/homebrew/bin/brew shellenv)
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(direnv python git git-flow pip postgres tmux docker docker-compose)

source $ZSH/oh-my-zsh.sh
#eval "$(pipenv --completion)"

#GPG config
GPG_TTY=$(tty)
export GPG_TTY
if [ -z "${SSH_TTY}" ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

# Customize to your needs...
#alias vim='/usr/local/Cellar/vim/7.4.052/bin/vim'
alias gf='git flow '
alias gcm='git commit -m'
alias gckm='git checkout master'
alias gckd='git checkout develop'
alias gpt='git push --tags'
alias gmm='git merge master'
alias gmd='git merge develop'
alias gba='git branch -a'
alias gt='git tag'
alias grbd='git rebase develop'
alias gdf='git diff '

alias gck='git checkout'
alias gc='git commit '
alias gs='git status'
alias glog='git log --oneline --decorate --all --graph '
alias gm='git merge'
alias gp='git push'
alias grb='git rebase'
alias ga='git add'
alias gpl='git pull'
alias gsth='git stash'
alias glg="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glc='git log ORIG_HEAD.. --stat --no-merges'
alias glol='git log --graph --decorate --pretty=oneline --abbrev-commit'
alias glola='git log --graph --decorate --pretty=oneline --abbrev-commit --all'
alias gll='git log --graph --date=short'
# Worktree
alias gw='git worktree'
alias gwl='git worktree list'
alias gwa='git worktree add'
alias gwr='git worktree remove'
alias gwp='git worktree prune'

# Branch
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gsw='git switch'
alias gswc='git switch -c'

# Stash (completing the set)
alias gstl='git stash list'
alias gstp='git stash pop'
alias gstd='git stash drop'

# Rebase helpers
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase -i'

# Fetch
alias gfa='git fetch --all --prune'

# Cherry-pick
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'

alias gmt='git mergetool'
alias py='ipython'
#alias postgres.server="sudo -u postgres /Library/PostgreSQL/9.2/bin/pg_ctl -D/Library/PostgreSQL/9.2/data -m fast"
alias gpa='git remote update && git checkout main && git merge origin/main && git checkout develop && git merge origin/develop'
alias tmux="TERM=screen-256color-bce tmux"
# Docker
alias dkc="docker builder prune && docker images | grep 'none' | awk '{print $3}' | xargs docker rmi -f"
alias dc="docker-compose"

alias yf="gpg-connect-agent updatestartuptty /bye"
#python
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
[[ -f /usr/bin/virtualenvwrapper.sh ]] && source /usr/bin/virtualenvwrapper.sh
[[ -f /usr/local/bin/virtualenvwrapper.sh ]] && source /usr/local/bin/virtualenvwrapper.sh
eval "$(pyenv init -)"

#Path to Scala
#export LC_ALL="en_US.utf-8"
#export SCALA_HOME=/usr/local/scala
#export PATH=$PATH:$SCALA_HOME/bin

#Path to NVM
#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# RUST
export PATH="$HOME/.cargo/bin:$PATH"
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
#export SDKMAN_DIR="/Users/jesuejunior/.sdkman"
#[[ -s "${HOME}/.sdkman/bin/sdkman-init.sh" ]] && source "${HOME}/.sdkman/bin/sdkman-init.sh"

#TODO: create a if it is mac or linux
# Compiler flags — merged to avoid later assignments overwriting earlier ones
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"
export PATH="/opt/homebrew/opt/postgresql@13/bin:$PATH"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

export LDFLAGS="-L/opt/homebrew/opt/libpq/lib -L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/opt/postgresql@13/lib -L/opt/homebrew/opt/libxml2/lib -L/opt/homebrew/opt/libxslt/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libpq/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/postgresql@13/include -I/opt/homebrew/opt/libxml2/include -I/opt/homebrew/opt/libxslt/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/libpq/lib/pkgconfig"

# MYSQL client
#export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

# Work — keep secrets out of dotfiles; set tokens in ~/.zshrc_secrets (gitignored)
export GITHUB_USER=jesuejunior
#export GITHUB_USER_TOKEN=
#export SLACK_TOKEN=

#export PATH="/opt/homebrew/opt/scala@2.12/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jesue/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jesue/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jesue/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jesue/google-cloud-sdk/completion.zsh.inc'; fi

# Load secrets (tokens, PATs) from a gitignored file
[[ -f ~/.zshrc_secrets ]] && source ~/.zshrc_secrets


# Docker Desktop CLI completions — fpath must be set before oh-my-zsh's compinit runs,
# but since oh-my-zsh already called compinit, just register the path here.
fpath=(/Users/jesue/.docker/completions $fpath)

# dbt — use virtualenv's dbt-core when inside one, otherwise dbt Fusion
alias dbtf=/Users/jesue/.local/bin/dbt
function dbt() {
  if [[ -n "$VIRTUAL_ENV" && -f "$VIRTUAL_ENV/bin/dbt" ]]; then
    "$VIRTUAL_ENV/bin/dbt" "$@"
  else
    /Users/jesue/.local/bin/dbt "$@"
  fi
}
eval "$(direnv hook zsh)"

