#HOME=$HOME/.dropbox_ezlearn /Applications/Dropbox.app/Contents/MacOS/Dropbox &
export HOME
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="jj"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(python git vitualenvwrapper git-flow github django pip npm node postgres tmux vagrant debian docker docker-compose pep8 gulp nvm themes zsh-nvm )

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
#alias vim='/usr/local/Cellar/vim/7.4.052/bin/vim'
alias gf='git flow '
alias gcm='git commit -m'
alias gckm='git checkout master'
alias gckd='git checkout develop'
alias gpt='git push --tags'
alias gmm='git merge master'
alias gmd='git merge develop'
alias gba='git branch -a'
alias gt='git tag'
alias grbd='git rebase develop'
alias gdf='git diff '

alias gck='git checkout'
alias gc='git commit '
alias gs='git status'
alias glog='git log --oneline --decorate --all --graph '
alias gm='git merge'
alias gp='git push'
alias grb='git rebase'
alias ga='git add'
alias gpl='git pull'
alias gsth='git stash'
alias glg="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glc='git log ORIG_HEAD.. --stat --no-merges'
alias glol='git log --graph --decorate --pretty=oneline --abbrev-commit'
alias glola='git log --graph --decorate --pretty=oneline --abbrev-commit --all'
alias gll='git log --graph --date=short'
alias py='ipython'
alias postgres.server="sudo -u postgres /Library/PostgreSQL/9.2/bin/pg_ctl -D/Library/PostgreSQL/9.2/data -m fast"
alias gpa='git remote update && git checkout master && git merge origin/master && git checkout develop && git merge origin/develop'
alias tmux="TERM=screen-256color-bce tmux"


#For virtualenvwrapper
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'


[[ -f /usr/bin/virtualenvwrapper.sh ]] && source /usr/bin/virtualenvwrapper.sh

[[ -f /usr/local/bin/virtualenvwrapper.sh ]] && source /usr/local/bin/virtualenvwrapper.sh

#PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

#Pat hto scala
export LC_ALL="en_US.utf-8"
export SCALA_HOME=/usr/local/scala
export PATH=$PATH:$SCALA_HOME/bin

export NVM_DIR="~/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
